### ISSUE TITLE
Invalid ix value for unmodifiable point

### ISSUE THREAD

**Issue by tpiotrow** [gallandarakhneorg/afc#32]
org.arakhne.afc.math.geometry.d2.i.Point2i#toUnmodifiable : line 270 - 273

    @Override
    public int iy() {
        return Point2i.this.ix();
    }

should be

    @Override
    public int iy() {
        return Point2i.this.iy();
    }

? Please let me know if this is the correct format to report such details, or if I shall correct them in my own fork (I detected this when I started 3D)

**Comment by gallandarakhneorg** [comment]
That's the correct form for bug reports. I will fix it is the master branch asap, and add the unit tests on "immutable points" because they are not yet created.
