### ISSUE TITLE
Redundant code in RectangularShape2dfx

### ISSUE THREAD

**Issue by tpiotrow** [gallandarakhneorg/afc#34]
Methods 
 get / set MinMax X /Y of RectangularShape2dfx are duplicates of the methods in AbstractRectangularShape2dfx.
RectangularShape2dfx could inherit from AbstractRectangularShape2dfx.

**Comment by gallandarakhneorg** [comment]
This is a old inheritance due to loops in the compiler unit dependency. It should be fixed now we have a clean type hierarchy type.
