### ISSUE TITLE
Create ArcPathElement2d and ArcPathElement2dfx

### ISSUE THREAD

**Issue by sebpetit** [gallandarakhneorg/afc#38]
The constructors can be :
`ArcPathElement2fp(double fromx, double fromy, double radiusx, double radiusy, double tox, double toy)`
`ArcPathElement2fx(DoubleProperty fromx, DoubleProperty fromy, DoubleProperty radiusx, DoubleProperty radiusy, DoubleProperty tox, DoubleProperty toy)`

**Comment by gallandarakhneorg** [comment]
The creation of these path elements will be done through the following function on paths:
* `arcTo(double radiusx, double radiusy, double tox, double toy)`

**Comment by sebpetit** [comment]
Is it possible to create an `ArcPathElement2fx` in `PathElement2dxf` to differentiate it from `CurvePathElement2fx` ?

In FXTL, in `PathShape2D`, we need to know when a `PathElement2dfx` has an `ARC_TO` type to create an `ArcTo` JavaFX object. We create `CubicCurveTo` objects when a `PathElement2dfx` has a `CURVE_TO` type.

**Comment by gallandarakhneorg** [comment]
The JavaFX `Path2D` is creating a curve when its `arcTo` function is called. It means that a JavaFX `Path2D` never replies `ArcTo` path elements. Indeed, `ArcTo` path element exists in JavaFX, but is is created only by the `PieChart` region.

However, I may add this new type of path element, that will be at the end mapped to a curve.
