### ISSUE TITLE
Add method that reply if a given shape is inside another shape

### ISSUE THREAD

**Issue by sebpetit** [gallandarakhneorg/afc#60]
The following method will be added : 

`Shape2D.contains(Shape2D)`

**Comment by sebpetit** [comment]
Examples of use cases :

```
Path2dfx path1 = new Path2dfx();
path1.moveTo(204.0, 193.5);
path1.lineTo(204.0, 85.5);
path1.lineTo(268.0, 85.5);
path1.lineTo(268.0, 149.5);
path1.lineTo(388.0, 149.5);
path1.lineTo(388.0, 193.5);
path1.closePath();
```

• ```
Path2dfx path2 = new Path2dfx();
path2.moveTo(288.0, 145.5);
path2.moveTo(388.0, 145.5);
path2.moveTo(388.0, 93.5);
path2.moveTo(288.0, 93.5);
path2.closePath();
```

`path1.contains(path2)` replies `false`.

• ```
Path2dfx path3 = new Path2dfx();
path3.moveTo(292.0, 185.5);
path3.moveTo(340.0, 185.5);
path3.moveTo(340.0, 153.5);
path3.moveTo(292.0, 153.5);
```

`path1.contains(path3)` replies `true`.

• `Segment2dfx segment1 = new Segment2dfx(372.0, 169.5, 372.0, 255.2);`

`path1.intersects(segment1)` replies `true` but `path1.contains(segment1)` replies `false`.

--------------------------------------------------------------------------------------------------

```
Path2dfx path3 = new Path2dfx();
path3.moveTo(14.0, 285.5);
path3.lineTo(74.0, 285.5);
path3.lineTo(74.0, 139.5);
path3.lineTo(180.0, 139.5);
path3.lineTo(180.0, 285.5);
path3.lineTo(224.0, 285.5);
path3.lineTo(224.0, 139.5);
path3.lineTo(390.0, 139.5);
path3.lineTo(390.0, 49.5);
path3.lineTo(14.0, 49.5);
path3.closePath();
```

• ```
Path2dfx path4 = new Path2dfx();
path4.moveTo(228.0, 239.5);
path4.moveTo(224.0, 239.5);
path4.moveTo(224.0, 257.5);
path4.moveTo(228.0, 257.5);
path4.closePath();
```

`path3.intersects(path4)` replies `true` but `path3.contains(path4)` replies` false`.

• `Circle2dfx circle1 = new Circle2dfx(324.0, 93.5, 5.66);`
`path3.intersects(circle1)` replies `true`.

--------------------------------------------------------------------------------------------------

```
Path5 path5 = new Path2dfx();
path5.moveTo(286.0, 131.5);
path5.lineTo(286.0, 111.5);
path5.arcTo(282.0, 111.5, 2.0, 2.0, 0.0, true, false);
path5.lineTo(282.0, 131.5);
path5.arcTo(286.0, 131.5, 2.0, 2.0, 0.0, true, false);
path5.closePath();
```

• `Circle2dfx circle2 = new Circle2dfx(284.0, 133.5, 0.725);`
`path5.intersects(circle2)` replies `true`, but `path5.contains(circle2)` replies `false`.

**Comment by gallandarakhneorg** [comment]
Use cases are passing, except that `assertTrue(path3.intersects(path4));` must be `assertFalse(path3.intersects(path4))` due to the assumption that shapes with only one common border are not intersecting.

**Comment by sebpetit** [comment]
I detected a case that does'nt work.

`Path2dfx path = new Path2dfx();`
`path.moveTo(168.0, 145.0);`
`path.lineTo(200.0, 200.0);`
`path.lineTo(200.0, 129.0);`
`path.lineTo(168.0, 129.0);`
`path.closePath();`

`Segment2dfx segment = new Segment2dfx(420.0, 297.0, 420.0, 0.0);`

Must be `assertFalse(segment.contains(path));` and not `assertTrue(segment.contains(path));`.

Can you check it, please ?
Thanks.
